---
title: "Homework 3"
format:
  html:
    theme: default
---



```{r}
library(shiny)
#install.packages("shinythemes")
library(shinythemes)
library(tidyverse)

data("faithful")
df <- faithful

df1 <- faithful %>%
  summarize(count = n()) %>%
  arrange(desc(count))

```


```{r}
#ui <- fluidPage(theme = shinytheme("yeti"),
  
#  titlePanel("Old Faithful Geyser Data"),
  
#  sidebarLayout(

#    sidebarPanel(
#      selectInput("stormStatus",
#                  label = "Filter by storm type: ",
#                  choices = unique(stormNames$status))
#    ),
#    
#    mainPanel(
#      p("Histogram of Waiting Times"),
#      plotOutput("nameDist"),
#      
#    )
#  )
#)

#server <- function(input, output, session) {
  
  
#  output$nameDist <- renderPlot({
    
#    str(input$stormStatus)
    
#    names_filtered <- filter(stormNames, status == input$stormStatus)
#    hist(names_filtered$count)

#  },
#  width = 400, height = 300)
  
#  output$nameTable <- renderTable({
    
#    names_filtered <- filter(stormNames, status == input$stormStatus)
#    head(names_filtered, 20)
    
#  })
  
#}

#shinyApp(ui, server)
```

